name: "Install Build Dependencies"
description: "Install vcpkg libraries and Qt environment for cross-platform builds"

inputs:
  vcpkg_libs:
    description: "vcpkg libraries to install"
    required: false
    default: "breakpad crashpad openssl tl-expected"
    type: string
  qt_modules:
    description: "Qt modules to install"
    required: false
    default: "qt5compat qtnetworkauth qtimageformats"
    type: string
  qt_ver:
    description: "Qt version to install"
    required: false
    default: "6.10.0"
    type: string

runs:
  using: "composite"

  steps:
    - name: Install Custom VCPKG
      uses: RealChuan/install-vcpkg@main

    - name: Delete vcpkg.json
      shell: bash
      run: |
        rm vcpkg.json

    - name: Cache windows vcpkg
      if: runner.os == 'Windows'
      uses: actions/cache@v4
      with:
        path: C:\vcpkg\installed
        key: ${{ runner.os }}-vcpkg-installed-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-installed-
          ${{ runner.os }}-vcpkg-

    - name: Cache macos or linux vcpkg
      if: runner.os == 'macOS' || runner.os == 'Linux'
      uses: actions/cache@v4
      with:
        path: /usr/local/share/vcpkg/installed
        key: ${{ runner.os }}-vcpkg-installed-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-installed-
          ${{ runner.os }}-vcpkg-

    - name: Install dependencies on windows
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install innosetup
        ninja --version
        cmake --version
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet x64-windows || (cat C:/vcpkg/installed/vcpkg/issue_body.md && exit 1)
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet x64-windows-static-md || (cat C:/vcpkg/installed/vcpkg/issue_body.md && exit 1)

    - name: Install dependencies on macos
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install python-setuptools tree
        ninja --version
        cmake --version
        clang --version
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet x64-osx || (cat /usr/local/share/vcpkg/installed/vcpkg/issue_body.md && exit 1)
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet arm64-osx || (cat /usr/local/share/vcpkg/installed/vcpkg/issue_body.md && exit 1)

    - name: Install dependencies on linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build build-essential libgl1-mesa-dev clang lintian tree fakeroot
        ninja --version
        cmake --version
        gcc --version
        vcpkg install ${{ inputs.vcpkg_libs }} --triplet x64-linux || (cat /usr/local/share/vcpkg/installed/vcpkg/issue_body.md && exit 1)

    - name: Setup Linux deployment tools
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install -y libfuse2 libxcb-cursor0
        wget -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" \
          -O /usr/local/bin/linuxdeployqt
        sudo chmod +x /usr/local/bin/linuxdeployqt

    - name: Build libtiff.so.5 on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        chmod +x packaging/ubuntu/build_libtiff.sh
        packaging/ubuntu/build_libtiff.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ inputs.qt_ver }}
        modules: ${{ inputs.qt_modules }}
        cache: true
