#!/bin/bash -ex
# 让 LaunchServices 立即识别新装 App
/usr/bin/touch "/Applications/Qt-App.app"

# 清可能残留的缓存
rm -rf "/Library/Caches/org.youth.Qt-App" || true

# 给安装日志写一条
logger -t Qt-App "postinstall finished (v0.2.1)"

exit 0