; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Qt-App"
#define MyAppVersion "0.2.1"
#define MyAppFileVersion "0.2.1.0" 
#define MyAppPublisher "The Youth."
#define MyAppURL "https://github.com/RealChuan/Qt-App"
#define MyAppExeName MyAppName + ".exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define MyAppUninstallName "Uninstall"
#define MyAppId "F9328618-8855-4E59-BD15-12C77B74E3C0"

#define MyCrashAppName "CrashReport"
#define MyCrashAppExeName "CrashReport.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{{#MyAppId}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
; AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=..\..\LICENSE
InfoBeforeFile=..\..\LICENSE
InfoAfterFile=..\..\README.md
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=..\releases
OutputBaseFilename={#MyAppName}_installer
SetupIconFile=..\..\src\apps\app\app.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
MinVersion=10.0
DefaultGroupName={#MyAppName}
Uninstallable=yes
UninstallDisplayName={#MyAppName}

; --- 版本信息修正 ---
VersionInfoCompany={#MyAppPublisher}
VersionInfoCopyright={#MyAppPublisher}
VersionInfoDescription={#MyAppName}
VersionInfoOriginalFileName={#MyAppExeName}
VersionInfoVersion={#MyAppFileVersion}
VersionInfoProductVersion={#MyAppFileVersion}
VersionInfoProductTextVersion={#MyAppVersion}
VersionInfoTextVersion={#MyAppVersion}
; -------------------

ShowLanguageDialog=auto
; SignTool = sha256
; SignedUninstaller = yes

ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

CloseApplications=yes
RestartApplications=no

[Languages]
Name: "Chinese"; MessagesFile: "ChineseSimplified.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone
Name: "vcredist"; Description: "Install Microsoft Visual C++ Redistributable"; GroupDescription: "Additional Runtimes"; Flags: unchecked

[Files]
Source: "..\packet\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\{#MyCrashAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\plugins\*"; DestDir: "{app}\plugins"; Flags: ignoreversion createallsubdirs recursesubdirs
Source: "..\packet\resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion createallsubdirs recursesubdirs
Source: "..\packet\translations\*"; DestDir: "{app}\translations"; Flags: ignoreversion createallsubdirs recursesubdirs
Source: "..\packet\aggregation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\crashpad_handler.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\d3dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\dump.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\dxcompiler.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\dxil.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\extensionsystem.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\libcrypto-3-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\libssl-3-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\opengl32sw.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\Qt6Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\Qt6Core5Compat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\Qt6Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\Qt6Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\Qt6Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\Qt6Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\resource.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\spinner.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\tasking.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\thirdparty.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\utils.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\vc_redist.x64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\packet\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.29.30133\x86\Microsoft.VC142.CRT\*"; DestDir: "{app}"; Flags: ignoreversion createallsubdirs recursesubdirs
; Source: "C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x86\*"; DestDir: "{app}"; Flags: ignoreversion createallsubdirs recursesubdirs

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

Root: HKA; Subkey: "SOFTWARE\Classes\CLSID\{{{#MyAppId}}"; ValueType: string; ValueData: "{#MyAppName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "SOFTWARE\Classes\CLSID\{{{#MyAppId}}\DefaultIcon"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"""; Flags: uninsdeletekey
Root: HKA; Subkey: "SOFTWARE\Classes\CLSID\{{{#MyAppId}}\shell\Open\Command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey
Root: HKA; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{{{#MyAppId}}"; ValueType: string; ValueData: "{#MyAppName}"; Flags: uninsdeletekey

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{#MyAppUninstallName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "Installing Microsoft Visual C++ Runtime ..."; Flags: runhidden waituntilterminated skipifdoesntexist; Tasks: vcredist
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName}"" program=""{app}\{#MyAppExeName}"" "; Flags: runhidden
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyAppName}"" program=""{app}\{#MyAppExeName}"" dir=in action=allow enable=yes"; Flags: runhidden
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyCrashAppName}"" program=""{app}\{#MyCrashAppExeName}"" "; Flags: runhidden
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall add rule name=""{#MyCrashAppName}"" program=""{app}\{#MyCrashAppExeName}"" dir=in action=allow enable=yes"; Flags: runhidden
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyAppName}"" program=""{app}\{#MyAppExeName}"""; Flags: runhidden; RunOnceId: "DelQtAppFirewallRule"
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#MyCrashAppName}"" program=""{app}\{#MyCrashAppExeName}"""; Flags: runhidden; RunOnceId: "DelCrashAppFirewallRule"

[UninstallDelete]
Type: filesandordirs; Name: "{app}\_"
Type: filesandordirs; Name: "{localappdata}\Youth\{#MyAppName}"
Type: filesandordirs; Name: "{localappdata}\Youth\{#MyCrashAppName}"

[Code]
// 检查进程是否正在运行
function IsProcessRunning(const ExeName: string): Boolean;
var
  ResultCode: Integer;
begin
  Result := Exec(
    ExpandConstant('{cmd}'),
    '/C tasklist /FI "IMAGENAME eq ' + ExeName + '" | find /I "' + ExeName + '" > nul',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
end;

// 安全结束进程
function KillProcess(const ExeName: string): Boolean;
var
  ResultCode: Integer;
begin
  Result := Exec(
    ExpandConstant('{cmd}'),
    '/C taskkill /F /IM "' + ExeName + '"',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  // taskkill 对不存在的进程通常返回 128，也视为成功
  Result := Result and ((ResultCode = 0) or (ResultCode = 128));
end;

// 停止所有相关进程
function StopProcesses: Boolean;
begin
  Result := True;
  if IsProcessRunning('{#MyAppExeName}') then
    if not KillProcess('{#MyAppExeName}') then Result := False;
  if IsProcessRunning('{#MyCrashAppExeName}') then
    if not KillProcess('{#MyCrashAppExeName}') then Result := False;
  if IsProcessRunning('crashpad_handler.exe') then
    if not KillProcess('crashpad_handler.exe') then Result := False;
end;

// 安装前准备：关闭正在运行的进程
function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  if not StopProcesses then
    Result := '无法关闭正在运行的 {#MyAppName} 相关进程，请手动关闭后重试。';
end;

// 卸载初始化：关闭正在运行的进程
function InitializeUninstall(): Boolean;
begin
  Result := StopProcesses;
  if not Result then
    MsgBox('无法关闭正在运行的 {#MyAppName} 相关进程，请手动关闭后重试。', mbError, MB_OK);
end;
