#!/bin/sh -e

APP_NAME="Qt-App"

# 升级/安装前先优雅退出
pkill -TERM -x ${APP_NAME} 2>/dev/null || true
sleep 1
pkill -KILL -x ${APP_NAME} 2>/dev/null || true
pkill -TERM -x CrashReport 2>/dev/null || true
pkill -KILL -x CrashReport 2>/dev/null || true

# 删除桌面快捷方式
rm -f ~/.local/share/applications/${APP_NAME}.desktop || true

exit 0
